name: Check Docker Base Image

on:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  docker:
    name: Ckeck Base Image and build if needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if update available
        id: check
        uses: azuresrv/docker-image-update-checker@main
        with:
          base-image: library/alpine:3.16
          image: ghcr.io/hoellenwesen/docker-internet-speedtest:latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          # relative path to the place where source code with Dockerfile is located
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          # Note: tags has to be all lower-case
          tags: ghcr.io/hoellenwesen/docker-internet-speedtest:latest
          # build on feature branches, push only on master branch
          push: true
        if: steps.check.outputs.needs-updating == 'true'

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}